version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/waste_platform.conf:/etc/nginx/conf.d/default.conf:ro

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #     PGHOST: localhost
  #   ports:
  #     - "5432:5432"
  #   # volumes:
  #     # - postgres_data:/var/lib/postgresql/data
  #     # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
  #   networks:
  #     - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    # depends_on:
      # - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge